### ISSUE TITLE
hello, i use  pre-processor not working

### ISSUE THREAD

**Issue by shaofq** [beamline/conformance-behavioural-patterns#1]
D:\soft\jdk-11.0.15.1_windows-x64_bin\jdk-11.0.15.1\bin\java.exe -jar D:\work\workspace\prcocessmining\conformance-behavioural-patterns-master\conformance-behavioural-patterns-master\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar D:\work\workspace\product\FlinkMiningProcess_platform\MiningProcessDemo\src\main\resources\data\apt.tpn C:\Users\ROG\AppData\Local\Temp\coverability1825484149459852642cg

this not working

**Comment by delas** [comment]
Hi. Could you please let me know what happens when you run the command?

**Comment by shaofq** [comment]
After execution, it has been in the waiting state, and there is no output result

**Comment by delas** [comment]
Could you share the files with me? Or, if the data cannot be shared, can you try with some publicly available files so I can reproduce the problem myself?

**Comment by shaofq** [comment]
`
public class CheckinfoExample {

    public static void main(String[] args) throws Exception {
        SimpleConformance conformance = new SimpleConformance(new File("D:\\work\\workspace\\product\\FlinkMiningProcess_platform\\MiningProcessDemo\\src\\main\\resources\\data\\apt.tpn"));
        XesLogSource source = new XesLogSource("D:\\work\\workspace\\product\\FlinkMiningProcess_platform\\MiningProcessDemo\\src\\main\\resources\\data\\444.xes");
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env
                .addSource(source)
                .keyBy(BEvent::getTraceName)
                .flatMap(conformance)
                .addSink(new SinkFunction<SimpleConformance.ConformanceResponse>(){
                    public void invoke(SimpleConformance.ConformanceResponse value, Context context) throws Exception {
                        System.out.println(
                                value.getCost() + " - " +
                                        value.getLastEvent().getEventName() + " - " +
                                        value.getLastEvent().getTraceName());
                    };
                });
        env.execute();
    }
}`

![image](https://user-images.githubusercontent.com/28698892/185794794-b4764765-d68b-4c64-801d-66a325acb48b.png)

this is my code,but is not working

**Comment by delas** [comment]
Can you share files D:\\work\\workspace\\product\\FlinkMiningProcess_platform\\MiningProcessDemo\\src\\main\\resources\\data\\444.xes and D:\\work\\workspace\\product\\FlinkMiningProcess_platform\\MiningProcessDemo\\src\\main\\resources\\data\\apt.tpn ?

**Comment by shaofq** [comment]
[https://github.com/shaofq/dockerimages/blob/master/444.xes](url)
[https://github.com/shaofq/dockerimages/blob/master/apt.tpn](url)

**Comment by delas** [comment]
I tried to replicate your code but it does work as expected. Here's the output:
```
================================================================================
Using this Java interpreter: C:\Program Files\Java\jre1.8.0_341\bin\java.exe
Using this region-based-preprocessor: C:\Users\andbur\git\conformance-behavioural-patterns\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar
================================================================================
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/C:/Users/andbur/.m2/repository/org/apache/flink/flink-core/1.14.3/flink-core-1.14.3.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.apache.flink.api.java.ClosureCleaner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
C:\Program Files\Java\jre1.8.0_341\bin\java.exe -jar C:\Users\andbur\git\conformance-behavioural-patterns\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar C:\Users\andbur\Desktop\apt.tpn C:\Users\andbur\AppData\Local\Temp\coverability10101114171842097210cg
C:\Program Files\Java\jre1.8.0_341\bin\java.exe -jar C:\Users\andbur\git\conformance-behavioural-patterns\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar C:\Users\andbur\Desktop\apt.tpn C:\Users\andbur\AppData\Local\Temp\coverability7358179070978395703cg
C:\Program Files\Java\jre1.8.0_341\bin\java.exe -jar C:\Users\andbur\git\conformance-behavioural-patterns\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar C:\Users\andbur\Desktop\apt.tpn C:\Users\andbur\AppData\Local\Temp\coverability12406853597518904236cg
C:\Program Files\Java\jre1.8.0_341\bin\java.exe -jar C:\Users\andbur\git\conformance-behavioural-patterns\src\main\resources\pre-processor\region-based-conformance-offline-preprocessor-v2.jar C:\Users\andbur\Desktop\apt.tpn C:\Users\andbur\AppData\Local\Temp\coverability8977414826682859980cg
0 - Activity A - case_977
0 - Activity A - case_231
0 - Activity A - case_543
0 - Activity A - case_822
0 - Activity A - case_964
0 - Activity A - case_136
0 - Activity A - case_484
0 - Activity A - case_75
0 - Activity A - case_372
0 - Activity A - case_734
0 - Activity A - case_117
0 - Activity A - case_380
0 - Activity A - case_711
0 - Activity A - case_850
0 - Activity A - case_318
0 - Activity A - case_202
0 - Activity A - case_897
0 - Activity A - case_413
0 - Activity A - case_792
0 - Activity A - case_515
0 - Activity A - case_961
0 - Activity A - case_63
0 - Activity A - case_109
...
```

Have you tried to wait a bit until the pre-processing is over? I needed to wait maybe a couple of minutes. Also, in your picture, I do not see any error so I assume that this is the issue. If the problem persists, please open an issue where the error is indeed visible.

**Comment by shaofq** [comment]
i use region-based-conformance-offline-preprocessor-v1.jar ,it working ,but region-based-conformance-offline-preprocessor-v2.jar not working ,is there any difference between the two
